server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
  application:
    name: pixelgateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: registration-eureka/eureka
application:
  jwt:
    secretKey: veryverysecureveryverysecureveryverysecure
    tokenExpirationAfterDays: 1
    tokenPrefix: Bearer