server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
application:
  jwt:
    secretKey: veryverysecureveryverysecureveryverysecure
    tokenExpirationAfterDays: 1
    tokenPrefix: Bearer
    
spring:
   application:
      name: pixelgateway
spring:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: registration-eureka/eureka