application:
  serviceurl:
    userservice: http://pixels-user-microservice:8090
    storyservice: http://pixels-story-microservice:8102
    chatservice: http://pixels-chat-microservice:8103
    mediaservice: http://pixels-media-microservice:8101
    