server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
application:
  jwt:
    secretKey: veryverysecureveryverysecureveryverysecure
    tokenExpirationAfterDays: 1
    tokenPrefix: Bearer
  serviceurl:
    userservice: http://localhost:8090
    storyservice: http://localhost:8102
    chatservice: http://localhost:8103
    mediaservice: http://localhost:8101