server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
application:
  jwt:
    secretKey: veryverysecureveryverysecureveryverysecure
    tokenExpirationAfterDays: 1
    tokenPrefix: Bearer
  microservice:
    user: http://localhost:8090
    story: http://localhost:8102
    chat: http://localhost:8103
    media: http://localhost:8101